hmslincs/hmslincs

- re_run.sh
Tested on dev-lincs, ready to merge and load datasets to prod.
> Add datasets 20220 20231

- src/hms/pubchem/pubchem_compound_search.py
> update response code check to accept http 202

- django/db/models.py
- django/db/views.py
> Db 327 view initialization

- django/db/views.py
- in assert logic, now returning empty response if appropriate for search results,
- catching uncaught DatasetDNE exception
> fix http 404 errors and assertion logic in view

- django/adaptive_drug_resistance/templates/adaptive_drug_resistance/vips/index.html
Just deletes one big commented-out block
> decruft adaptive_.../vips/index.html

- requirements.txt
This is needed for the trail_threshold_variability build but I forgot
to add it previously.
> Add unipath to requirements.txt

- re_run.sh
groups/lincs/prod directory has been updated
> added datasets 20233 - 20235

- django/db/static/css/hmslincs.css
- django/db/views.py
> use CSS max-width property:

- django/db/views.py
- add the reagent fields to matched_text global sitesearchmanager
- add the reagent fields to matched_text in each specific reagent search manager
> resolves #377: show reagent fields in matched text:

- django/db/views.py
* use 1 based index range
* suppress form errors
> resolve #370: items_per_page:

- django/breast_cancer_signaling/templates/breast_cancer_signaling/index.html
- django/db/templates/db/index.html
- django/single_cell_dynamics/templates/single_cell_dynamics/index.html
A few final template content tweaks that I missed in the previous explore_architecture branch.
> General content updates

- django/db/views.py
> set the window name to "_blank" to open a new window on window open

- django/db/views.py
> fixes #382

- django/db/static/css/hmslincs.css
- django/db/static/db/js/main.js
- django/db/templates/db/base.html
- django/db/views.py
- django/hmslincs_server/settings.py
* should be ready for final review, deploy after Qualtrics survey is finalized.
> Db 402 popup feedback form

- django/db/static/css/hmslincs.css
- django/db/views.py
Addresses path errors with smallmolecule sort and download filenames
> Db 408 resolve ui path errors

- re_run.sh
datasets 20244 - 20252 added to re_run loading script
> added datasets 20244 - 20252

- django/db/static/css/hmslincs.css
- django/db/templates/db/detailListing.html
- django/db/templates/db/smallMoleculeDetail.html
- django/db/views.py
- sampledata/sample_small_molecules.sdf
- src/import_smallmolecule.py
> Db detail view image placement and layout, batch sort order

- django/hmslincs_server/settings.py
> set log level to WARN

- django/hmslincs_server/settings.py
> add caching and timeout for webtemplates, resolves #427

- re_run.sh
added datasets 20205, 20214, 20259, 20260 to loading script; added
primary cell importer and other reagent importer
> added datasets and primary cell importer

- django/db/views.py
resolves #433 
@jmuhlich - this should be ready, tested on dev.
> check psycopg cursor values against None for export

- sampledata/sample_small_molecules.sdf
- src/import_smallmolecule.py
resolves #431 
@jmuhlich tested locally - this will have no impact until new data are loaded.
> add date fields to the small molecule importer

- django/db/views.py
- fixes for uncaught exceptions on the production server
> DB fixes for errors in admin email logs

- re_run.sh
Added 4 datasets to re_run.sh loading script.
> added datasets 20261-20264

- django/db/api.py
resolves #451
@jmuhlich this is tested on dev.lincs and should be ready.
> use explicit ordering for api queries

- django/db/views.py
- src/import_dataset2.py
> Db 446 show batch ids in reagents studied

- re_run.sh
added datasets 20326-20337; added iPSC, differentiated cell, and
unclassified perturbagen importers
> added datasets 20326-20337

- deploy
- django/hmslincs_server/settings.py
- find_and_move_restricted_images.sh
- re_run.sh
- requirements.txt
- run.sh
- sbatch_wrapper_dev.sh
- update paths to /n/www
- remove h5py from the requirements
- set django-tables2 version for compatability
- disable pip install from build
- use the virtualenv_o2
- see #474
> updates for the O2 build environment:

- deploy
> resolves #412

- django/db/api.py
- fixes bug on dataset metadata tab
> remove empty imaging entry in metadata

- django/db/static/css/hmslincs.css
- django/db/static/db/js/main.js
- django/db/templates/db/smallMoleculeDetail.html
- django/db/views.py
- src/import_dataset2.py
- implement the new TAS study (#20000)
- new Target Affinity table in the small molecule detail page
@jmuhlich
> Issue 489 tas study
